### ISSUE TITLE
Обновить карту Трамвайный город

### ISSUE THREAD

**Issue by Trollebas** [hikayamasan353/TrancityPatch#1]
[Трамвайный город.zip](https://github.com/hikayamasan353/TrancityPatch/files/11122680/default.zip)
Произведён монтаж КС по всей карте.
Автор, можно ли с вами как-то связаться? Имею доступ к самому большому сообществу по Trancity в ВК, а так же как вы уже знаете - пытался доработать игру в мелочах.

**Comment by hikayamasan353** [comment]
Обновил, теперь она есть в релизе.
